spring:
  profiles:
      active:
        -  dog
        -  EN
        -  prod

guru:
    username: YmlUserName
    password: YmlPassword
    jdbcUrl: YmlUrl

---
spring:
  config:
    activate:
      on-profile: prod

guru:
  username: ProdYmlUserName
  password: ProdYmlPassword
  jdbcUrl: ProdYmlUrl

